export const ROUTES = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  DASHBOARD: 'DASHBOARDHOME',
  EVENTS: 'EVENTS',
  PROFILE: 'PROFILE',
  ADDEVENT: 'ADDEVENT',
  DashboardStackScreen: 'DASHBOARD',
} as const;
