export const ROUTES = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  DASHBOARD: 'DASHBOARD_SCREEN',
  EVENTS: 'EVENTS_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  ADD_EVENT: 'ADD_EVENT',
  DASHBOARD_STACK_SCREEN: 'DASHBOARD',
  EVENT_DETAILS: 'EVENT_DETAILS',
  EVENT_STACK_SCREEN: 'EVENTS',
  SETTINGS:'SETTINGS',
  PROFILE_STACK_SCREEN:'PROFILE'
} as const;
