export const ROUTES = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  DASHBOARD: 'DASHBOARDHOME',
  EVENTS: 'EVENTS',
  PROFILE: 'PROFILE',
  ADD_EVENT: 'ADD_EVENT',
  DASHBOARD_STACK_SCREEN: 'DASHBOARD',
} as const;
